### ISSUE TITLE
question about joint orders and directions

### ISSUE THREAD

**Issue by elpimous** [mfclabber/quad-sdk_go1#3]
Hi friend, good work.
Could I ask for quad sdk joint orders ?

testing on my robot, not a unitree one.
all my controllers are clockwise. I seems that it's not thecase on unitree..

Could you share your sent joint order and their direction ? 
**mine are** : Fr_haa, Fr_hfe, Fr_kfe, Fl...., Hr..., HL...  ? (from 0 to 11)

**mine direction are** : (-++ --- +++ +--)

Really hope any help .
Thanks friend
Vincent

**Comment by mfclabber** [comment]
Hi! Files with the directions of rotation of the joints can be found in this [file](https://github.com/mfclabber/quad-sdk_go1/blob/quad-sdk-go1_real/quad_simulator/go1_description/xacro/leg.xacro)

**Comment by elpimous** [comment]
hello, sent you mail. would you take time to check and answer ? Thanks Dmitriy

**Comment by mfclabber** [comment]
> 

Ok

**Comment by mfclabber** [comment]
Perhaps in this file you will be able to find the changes you need
 unitree_go1_ros_driver.zip
<https://drive.google.com/file/d/1kOIdRwx_eybRgFv5LyhcbvoXw3_LC2JI/view?usp=drive_web>


вт, 12 сент. 2023 г. в 19:31, FOUCAULT Vincent ***@***.***>:

**Comment by elpimous** [comment]
thanks Dmitriy
